name: Update Manifesto

on:
  schedule:
    # Check for updates every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-manifesto:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout site repository
      uses: actions/checkout@v4
      
    - name: Fetch latest manifesto
      id: fetch-manifesto
      run: |
        # Fetch the latest manifesto from the repository
        curl -H "Accept: application/vnd.github.v3+json" \
             -H "User-Agent: CivicPress-Site-Updater" \
             "https://api.github.com/repos/CivicPress/manifesto/contents/manifesto.md?ref=master" \
             | jq -r '.content' | base64 -d > latest-manifesto.md
        
        # Check if content changed
        if [ -f "current-manifesto.md" ]; then
          if cmp -s "latest-manifesto.md" "current-manifesto.md"; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "no_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Update site if manifesto changed
      if: steps.fetch-manifesto.outputs.no_changes == 'false'
      run: |
        # Update the current manifesto
        cp latest-manifesto.md current-manifesto.md
        
        # Convert markdown to HTML for SEO
        # You could use a markdown converter here if needed
        
        # Commit and push changes
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add current-manifesto.md
        git commit -m "Update manifesto from repository" || exit 0
        git push 